DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTkwMDM5NzIsInVzZXJJZCI6MX0.lChFvrxTEMu0SXJ4PC3HIqV6nKF7L5TlN_q7VsCPjGo